MAIN-APP:
  URL: "http://localhost:8080"
  GET-ALL-WORKLOADS: "/trainings"

WORKLOAD-APP:
  URL: "http://localhost:8000"

MODIFY-WORKLOAD:
  URL: "http://workload-app/workloads"

WORKLOAD:
  REQUEST:
    QUEUE: "workload-request-queue"

  SINGLE:
    UPDATE:
      QUEUE: "workload.single.update.queue"

  BATCH:
    UPDATE:
      QUEUE: "workload.batch.update.queue"
